### PR TITLE
support for file names with period character

### PR DESCRIPTION
**Pull request by jpduckwo**

### CODE REVIEW

**Comment by jruchaud** [comment]
I was looking for the problem, but you're faster.

**Comment by jruchaud** [comment]
I think it is better to use [path.extname(path)
#](https://nodejs.org/api/path.html#path_path_extname_path).

**Comment by jpduckwo** [comment]
Ok yes good idea

**Comment by jpduckwo** [comment]
I'll leave with you to decide the best way as I'm not sure how it handle files without ext etc.

Cheers!

**Comment by jruchaud** [comment]
Ok I will check in my side.

**Pull request closed without merging**
